Create python-app.yml
Erez-Shlingbaum/Empire pull request #41
Opened 2022-01-01 16:07 UTC by Erez-Shlingbaum

2022-01-01 16:44 UTC, Erez-Shlingbaum commented
We should merge tests branch before this

2022-01-01 17:10 UTC, segalmatan requested changes

2022-01-01 17:10 UTC, segalmatan commented on .github/workflows/python-app.yml
> +        python-version: "3.10"
Are we using this version?

2022-01-02 17:31 UTC, segalmatan commented on .github/workflows/python-app.yml
> +    - name: Set up Python 3.10
fix version

2022-01-02 17:31 UTC, segalmatan commented on .github/workflows/python-app.yml
> +    - name: Set up Python 3.10
why have the version in the name?

2022-01-02 17:41 UTC, segalmatan approved these changes

2022-01-02 17:41 UTC, merged